use_frameworks!

target 'JQCollectionViewAlignLayout_Example' do
  pod 'JQCollectionViewAlignLayout', :path => '../'

  target 'JQCollectionViewAlignLayout_Tests' do
    inherit! :search_paths

    
  end
end
