workspace 'JQCollectionViewAlignLayout'

project 'JQCollectionViewAlignLayout-iOS/JQCollectionViewAlignLayout-iOS.xcodeproj'
project 'JQCollectionViewAlignLayout-macOS/JQCollectionViewAlignLayout-macOS.xcodeproj'
project 'JQCollectionViewAlignLayout-tvOS/JQCollectionViewAlignLayout-tvOS.xcodeproj'

target 'JQCollectionViewAlignLayout-iOS' do
  platform :ios, '9.0'
  pod 'JQCollectionViewAlignLayout', :path => '../'
  project 'JQCollectionViewAlignLayout-iOS/JQCollectionViewAlignLayout-iOS.xcodeproj'
end

target 'JQCollectionViewAlignLayout-macOS' do
  platform :osx, '10.11'
  pod 'JQCollectionViewAlignLayout', :path => '../'
  project 'JQCollectionViewAlignLayout-macOS/JQCollectionViewAlignLayout-macOS.xcodeproj'
end

target 'JQCollectionViewAlignLayout-tvOS' do
  platform :tvos
  pod 'JQCollectionViewAlignLayout', :path => '../'
  project 'JQCollectionViewAlignLayout-tvOS/JQCollectionViewAlignLayout-tvOS.xcodeproj'
end

